### ISSUE TITLE
Build everything failure on Windows 7

### ISSUE THREAD

**Issue by gjb2048** [peterpilgrim/javaee7-developer-handbook#1]
Hi Peter,

gradle build-everything is failing on Windows 7.  I'm running javac 1.7.0_51 and gradle 1.11.  Here is the output from the command line with the --stacktrace option:

Creating targetName=7942-jeh7hb-root-sources-0.98.zip
:install_glassfish-embedded
:glassfish-embedded:compileJava UP-TO-DATE
:glassfish-embedded:processResources UP-TO-DATE
:glassfish-embedded:classes UP-TO-DATE
:glassfish-embedded:jar UP-TO-DATE
:glassfish-embedded:sourcesJar UP-TO-DATE
:glassfish-embedded:assemble UP-TO-DATE
:glassfish-embedded:compileTestJava UP-TO-DATE
:glassfish-embedded:processTestResources UP-TO-DATE
:glassfish-embedded:testClasses UP-TO-DATE
:glassfish-embedded:test UP-TO-DATE
:glassfish-embedded:check UP-TO-DATE
:glassfish-embedded:build UP-TO-DATE
:glassfish-embedded:install
:build
:build_appendix04
:appendix04:compileJava UP-TO-DATE
:appendix04:processResources UP-TO-DATE
:appendix04:classes UP-TO-DATE
:appendix04:jar UP-TO-DATE
:appendix04:assemble UP-TO-DATE
:appendix04:compileTestJava UP-TO-DATE
:appendix04:processTestResources UP-TO-DATE
:appendix04:testClasses UP-TO-DATE
:appendix04:test UP-TO-DATE
:appendix04:check UP-TO-DATE
:appendix04:build UP-TO-DATE
:build_arquillian
:arquillian:compileJava UP-TO-DATE
:arquillian:processResources UP-TO-DATE
:arquillian:classes UP-TO-DATE
:arquillian:jar UP-TO-DATE
:arquillian:assemble UP-TO-DATE
:arquillian:compileTestJava UP-TO-DATE
:arquillian:processTestResources UP-TO-DATE
:arquillian:testClasses UP-TO-DATE
:arquillian:test UP-TO-DATE
:arquillian:check UP-TO-DATE
:arquillian:build UP-TO-DATE
:build_bean-validation
:bean-validation:compileJava UP-TO-DATE
:bean-validation:processResources UP-TO-DATE
:bean-validation:classes UP-TO-DATE
:bean-validation:jar UP-TO-DATE
:bean-validation:assemble UP-TO-DATE
:bean-validation:compileTestJava UP-TO-DATE
:bean-validation:processTestResources UP-TO-DATE
:bean-validation:testClasses UP-TO-DATE
:bean-validation:test UP-TO-DATE
:bean-validation:check UP-TO-DATE
:bean-validation:build UP-TO-DATE
:build_bean-validation-arquillian
:bean-validation-arquillian:compileJava UP-TO-DATE
:bean-validation-arquillian:processResources UP-TO-DATE
:bean-validation-arquillian:classes UP-TO-DATE
:bean-validation-arquillian:war UP-TO-DATE
:bean-validation-arquillian:assemble UP-TO-DATE
:bean-validation-arquillian:compileTestJava UP-TO-DATE
:bean-validation-arquillian:processTestResources UP-TO-DATE
:bean-validation-arquillian:testClasses UP-TO-DATE
:bean-validation-arquillian:test UP-TO-DATE
:bean-validation-arquillian:check UP-TO-DATE
:bean-validation-arquillian:build UP-TO-DATE
:build_ejb
:ejb:compileJava UP-TO-DATE
:ejb:processResources UP-TO-DATE
:ejb:classes UP-TO-DATE
:ejb:jar UP-TO-DATE
:ejb:assemble UP-TO-DATE
:ejb:compileTestJava UP-TO-DATE
:ejb:processTestResources UP-TO-DATE
:ejb:testClasses UP-TO-DATE
:ejb:test UP-TO-DATE
:ejb:check UP-TO-DATE
:ejb:build UP-TO-DATE
:build_glassfish-embedded
:glassfish-embedded:compileJava UP-TO-DATE
:glassfish-embedded:processResources UP-TO-DATE
:glassfish-embedded:classes UP-TO-DATE
:glassfish-embedded:jar UP-TO-DATE
:glassfish-embedded:sourcesJar UP-TO-DATE
:glassfish-embedded:assemble UP-TO-DATE
:glassfish-embedded:compileTestJava UP-TO-DATE
:glassfish-embedded:processTestResources UP-TO-DATE
:glassfish-embedded:testClasses UP-TO-DATE
:glassfish-embedded:test UP-TO-DATE
:glassfish-embedded:check UP-TO-DATE
:glassfish-embedded:build UP-TO-DATE
:build_jaxrs-basic
:jaxrs-basic:compileJava UP-TO-DATE
:jaxrs-basic:processResources UP-TO-DATE
:jaxrs-basic:classes UP-TO-DATE
:jaxrs-basic:war UP-TO-DATE
:jaxrs-basic:assemble UP-TO-DATE
:jaxrs-basic:compileTestJava UP-TO-DATE
:jaxrs-basic:processTestResources UP-TO-DATE
:jaxrs-basic:testClasses UP-TO-DATE
:jaxrs-basic:test UP-TO-DATE
:jaxrs-basic:check UP-TO-DATE
:jaxrs-basic:build UP-TO-DATE
:build_jms-essentials
:jms-essentials:compileJava UP-TO-DATE
:jms-essentials:processResources UP-TO-DATE
:jms-essentials:classes UP-TO-DATE
:jms-essentials:war UP-TO-DATE
:jms-essentials:assemble UP-TO-DATE
:jms-essentials:compileTestJava UP-TO-DATE
:jms-essentials:processTestResources UP-TO-DATE
:jms-essentials:testClasses UP-TO-DATE
:jms-essentials:test UP-TO-DATE
:jms-essentials:check UP-TO-DATE
:jms-essentials:build UP-TO-DATE
:build_jpa-criteria
:jpa-criteria:compileJava UP-TO-DATE
:jpa-criteria:processResources UP-TO-DATE
:jpa-criteria:classes UP-TO-DATE
:jpa-criteria:jar UP-TO-DATE
:jpa-criteria:assemble UP-TO-DATE
:jpa-criteria:compileTestJava UP-TO-DATE
:jpa-criteria:processTestResources UP-TO-DATE
:jpa-criteria:testClasses UP-TO-DATE
:jpa-criteria:test

je7hb.jpa.advanced.criteria.EmployeeCriteriaAdvancedSearchTest > classMethod FAILED
    org.jboss.arquillian.container.spi.client.container.LifecycleException

je7hb.jpa.advanced.criteria.EmployeeCriteriaDeleteTest > classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jboss.arquillian.container.spi.client.container.LifecycleException

je7hb.jpa.advanced.criteria.EmployeeCriteriaQueryTest > classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jboss.arquillian.container.spi.client.container.LifecycleException

je7hb.jpa.advanced.criteria.EmployeeCriteriaUpdateTest > classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.jboss.arquillian.container.spi.client.container.LifecycleException
:jpa-criteria:test FAILED
:build_jpa-criteria FAILED

BUILD FAILED

Total time: 29.394 secs

Kind regards,

Gareth

**Comment by peterpilgrim** [comment]
This is fixed.

**Comment by gjb2048** [comment]
Thank you Peter :)
