### ISSUE TITLE
Chapter 1 xentracker cannot find /view/index.xhtml

### ISSUE THREAD

**Issue by gjb2048** [peterpilgrim/javaee7-developer-handbook#2]
Hi Peter,

I'm trying to run xentracker-basic but '/view/index.xhtml' cannot be found:

![2014-04-23 12_31_59-error - _views_index xhtml not found in externalcontext as a resource](https://cloud.githubusercontent.com/assets/1058419/2776909/2cdf8f96-cadc-11e3-877a-57148e6aa972.png)

I'm using 'gradle run' from the command line and have also tried from within Netbeans and Eclipse with their gradle plugins.  Gradle is 1.11.  The command line output is:

:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
=================================================
=================================================
=================================================
Start the Server with a ShrinkWrap build here!!!!
test.war:
/index.html
/javascripts/
/javascripts/angular.js
/javascripts/angular.min.js
/javascripts/main.js
/javascripts/bootstrap.min.js
/javascripts/controllers.js
/javascripts/jquery-1.10.1.js
/javascripts/bootstrap.js
/styles/
/styles/bootstrap-responsive.css
/styles/bootstrap.css
/styles/main.css
/styles/bootstrap-responsive.min.css
/styles/bootstrap.min.css
/mockup.html
/images/
/images/glyphicons-halflings-white.png
/images/XeNoNiQUe-Logo-2011-01-233x175-72dpi.png
/images/xentracker_logon_signpost_retina.jpg
/images/twitter-bird-white-on-blue.png
/images/xentracker_logon_signpost.jpg
/images/glassfish_logo.jpg
/images/glyphicons-halflings.png
/images/Google-Plus-Logo.png
/working.html
/WEB-INF/
/WEB-INF/beans.xml
/WEB-INF/glassfish-resources.xml
/WEB-INF/web.xml
/WEB-INF/classes/
/WEB-INF/classes/je7hb/
/WEB-INF/classes/je7hb/intro/
/WEB-INF/classes/je7hb/intro/xentracker/
/WEB-INF/classes/je7hb/intro/xentracker/init/
/WEB-INF/classes/je7hb/intro/xentracker/init/DemoDataConfigurator.class
/WEB-INF/classes/je7hb/intro/xentracker/control/
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectEditController.class
/WEB-INF/classes/je7hb/intro/xentracker/control/WebSocketClientTesterEndpoint.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectWebSocketServerEndpoint$1.class
/WEB-INF/classes/je7hb/intro/xentracker/control/WebSocketClientTesterEndpoint$1.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectViewController.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectRESTServerEndpoint$1.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectHelper.class
/WEB-INF/classes/je7hb/intro/xentracker/control/TaskListViewController.class
/WEB-INF/classes/je7hb/intro/xentracker/control/TaskEditController.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectRESTServerEndpoint.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectRESTServerEndpoint$2.class
/WEB-INF/classes/je7hb/intro/xentracker/control/ProjectWebSocketServerEndpoint.class
/WEB-INF/classes/je7hb/intro/xentracker/boundary/
/WEB-INF/classes/je7hb/intro/xentracker/boundary/ProjectTaskService.class
/WEB-INF/classes/je7hb/intro/xentracker/entity/
/WEB-INF/classes/je7hb/intro/xentracker/entity/Task_.class
/WEB-INF/classes/je7hb/intro/xentracker/entity/Project_.class
/WEB-INF/classes/je7hb/intro/xentracker/entity/Task.class
/WEB-INF/classes/je7hb/intro/xentracker/entity/Project.class
/WEB-INF/classes/je7hb/intro/xentracker/StringHelper.class
/WEB-INF/classes/META-INF/
/WEB-INF/classes/META-INF/persistence.xml
/resources/
/resources/javascripts/
/resources/javascripts/bootstrap.min.js
/resources/javascripts/jquery-1.10.1.js
/resources/javascripts/bootstrap.js
/resources/javascripts/main.js
/resources/images/
/resources/images/twitter-bird-white-on-blue.png
/resources/images/glyphicons-halflings.png
/resources/images/xentracker_logon_signpost_retina.jpg
/resources/images/Google-Plus-Logo.png
/resources/images/glassfish_logo.jpg
/resources/images/xentracker_logon_signpost.jpg
/resources/images/XeNoNiQUe-Logo-2011-01-233x175-72dpi.png
/resources/images/glyphicons-halflings-white.png
/resources/styles/
/resources/styles/bootstrap-responsive.css
/resources/styles/bootstrap.min.css
/resources/styles/bootstrap.css
/resources/styles/main.css
/resources/styles/bootstrap-responsive.min.css
classpath[0] = C:\Users\Gareth\Documents\javaee7-developer-handbook-master\ch01\xentracker-basic\build\classes\main
classpath[1] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\joda-time\joda-time\2.2\a5f29a7acaddea3f4af307e8cf2d0cc82645fd7d\joda-time-2.2.jar
classpath[2] = C:\Users\Gareth\.m2\repository\com\javaeehandbook\book1\glassfish-embedded-runner\1.0\glassfish-embedded-runner-1.0.jar
classpath[3] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\org.jboss.shrinkwrap\shrinkwrap-api\1.0.1\83ee2ca1702d79ceda73634e33b0fac8e73acced\shrinkwrap-api-1.0.1.jar
classpath[4] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\org.jboss.shrinkwrap\shrinkwrap-impl-base\1.0.1\feb8c9e875222fae065b4c81937797b00c7ff347\shrinkwrap-impl-base-1.0.1.jar
classpath[5] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\org.glassfish.main.extras\glassfish-embedded-all\4.0.1-b01\9500528f0ecf0dea5fb3ff8a3619d506d389be8f\glassfish-embedded-all-4.0.1-b01.jar
classpath[6] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\javax\javaee-api\7.0\51399f902cc27a808122edcbebfaa1ad989954ba\javaee-api-7.0.jar
classpath[7] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\org.jboss.shrinkwrap\shrinkwrap-spi\1.0.1\4bcb163157366c0f690362594dfa4baed67a6152\shrinkwrap-spi-1.0.1.jar
classpath[8] = C:\Users\Gareth\.gradle\caches\modules-2\files-2.1\com.sun.mail\javax.mail\1.5.0\ec2410fdf7e0a3022e7c2a2e6241039d1abc1e98\javax.mail-1.5.0.jar
classpath[9] = C:\Users\Gareth\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar
Found populator: org.glassfish.kernel.embedded.EmbeddedDomainXml
[EL Config]: metadata: The access type for the persistent class [class je7hb.intro.xentracker.entity.Task] is set to [FIELD].
[EL Config]: metadata: The target entity (reference) class for the many to one mapping element [field project] is being defaulted to: class je7hb.intro.xentracker.entity.Project.
[EL Config]: metadata: The access type for the persistent class [class je7hb.intro.xentracker.entity.Project] is set to [FIELD].
[EL Config]: metadata: The target entity (reference) class for the one to many mapping element [field tasks] is being defaulted to: class je7hb.intro.xentracker.entity.Task.
[EL Config]: metadata: The alias name for the entity class [class je7hb.intro.xentracker.entity.Task] is being defaulted to: Task.
[EL Config]: metadata: The table name for entity [class je7hb.intro.xentracker.entity.Task] is being defaulted to: TASK.
[EL Config]: metadata: The column name for element [name] is being defaulted to: NAME.
[EL Config]: metadata: The column name for element [completed] is being defaulted to: COMPLETED.
[EL Config]: metadata: The alias name for the entity class [class je7hb.intro.xentracker.entity.Project] is being defaulted to: Project.
[EL Config]: metadata: The table name for entity [class je7hb.intro.xentracker.entity.Project] is being defaulted to: PROJECT.
[EL Config]: metadata: The column name for element [headline] is being defaulted to: HEADLINE.
[EL Config]: metadata: The column name for element [description] is being defaulted to: DESCRIPTION.
[EL Config]: metadata: The column name for element [name] is being defaulted to: NAME.
[EL Config]: metadata: The primary key column name for the mapping element [field project] is being defaulted to: PROJECT_ID.
[EL Config]: weaver: Class je7hb.intro.xentracker.entity.Project could not be weaved for change tracking as it is not supported by its mappings.
[EL Info]: EclipseLink, version: Eclipse Persistence Services - 2.5.0.v20130507-3faac2b
[EL Fine]: connection: Detected database platform: org.eclipse.persistence.platform.database.JavaDBPlatform
[EL Config]: connection: Connection(1693124029)--connecting(DatabaseLogin(
	platform=>DatabasePlatform
	user name=> ""
	connector=>JNDIConnector datasource name=>null
))
[EL Config]: connection: Connection(29749006)--Connected: jdbc:derby:/tmp/xentracker-basic/derby
	User: APP
	Database: Apache Derby  Version: 10.9.1.0 - (1344872)
	Driver: Apache Derby Embedded JDBC Driver  Version: 10.9.1.0 - (1344872)
[EL Config]: connection: Connection(1775337738)--connecting(DatabaseLogin(
	platform=>JavaDBPlatform
	user name=> ""
	connector=>JNDIConnector datasource name=>null
))
[EL Config]: connection: Connection(963571148)--Connected: jdbc:derby:/tmp/xentracker-basic/derby
	User: APP
	Database: Apache Derby  Version: 10.9.1.0 - (1344872)
	Driver: Apache Derby Embedded JDBC Driver  Version: 10.9.1.0 - (1344872)
[EL Info]: connection: file:/C:/Users/Gareth/AppData/Local/Temp/gfembed1863456500632231034tmp/applications/xentracker/WEB-INF/classes/_XenTracker login successful
[EL Fine]: sql: Connection(1676178363)--ALTER TABLE TASK DROP CONSTRAINT FK_TASK_PROJECT_ID
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'ALTER TABLE' cannot be performed on 'TASK' because it does not exist.
Error Code: 30000
Call: ALTER TABLE TASK DROP CONSTRAINT FK_TASK_PROJECT_ID
Query: DataModifyQuery(sql="ALTER TABLE TASK DROP CONSTRAINT FK_TASK_PROJECT_ID")
[EL Fine]: sql: Connection(1937609043)--DROP TABLE TASK
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'TASK' because it does not exist.
Error Code: 30000
Call: DROP TABLE TASK
Query: DataModifyQuery(sql="DROP TABLE TASK")
[EL Fine]: sql: Connection(811081896)--DROP TABLE PROJECT
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'PROJECT' because it does not exist.
Error Code: 30000
Call: DROP TABLE PROJECT
Query: DataModifyQuery(sql="DROP TABLE PROJECT")
[EL Fine]: sql: Connection(1294515158)--DROP TABLE TASK
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'TASK' because it does not exist.
Error Code: 30000
Call: DROP TABLE TASK
Query: DataModifyQuery(sql="DROP TABLE TASK")
[EL Fine]: sql: Connection(1290898322)--DROP TABLE PROJECT
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'PROJECT' because it does not exist.
Error Code: 30000
Call: DROP TABLE PROJECT
Query: DataModifyQuery(sql="DROP TABLE PROJECT")
[EL Fine]: sql: Connection(2133750055)--DROP TABLE TASK
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'TASK' because it does not exist.
Error Code: 30000
Call: DROP TABLE TASK
Query: DataModifyQuery(sql="DROP TABLE TASK")
[EL Fine]: sql: Connection(1471153681)--DROP TABLE PROJECT
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'PROJECT' because it does not exist.
Error Code: 30000
Call: DROP TABLE PROJECT
Query: DataModifyQuery(sql="DROP TABLE PROJECT")
[EL Fine]: sql: Connection(466899822)--DROP TABLE TASK
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'TASK' because it does not exist.
Error Code: 30000
Call: DROP TABLE TASK
Query: DataModifyQuery(sql="DROP TABLE TASK")
[EL Fine]: sql: Connection(1868993735)--DROP TABLE PROJECT
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'PROJECT' because it does not exist.
Error Code: 30000
Call: DROP TABLE PROJECT
Query: DataModifyQuery(sql="DROP TABLE PROJECT")
[EL Fine]: sql: Connection(676830044)--DROP TABLE TASK
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'TASK' because it does not exist.
Error Code: 30000
Call: DROP TABLE TASK
Query: DataModifyQuery(sql="DROP TABLE TASK")
[EL Fine]: sql: Connection(2011337234)--DROP TABLE PROJECT
[EL Fine]: sql: VALUES(1)
[EL Warning]: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.0.v20130507-3faac2b): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: 'DROP TABLE' cannot be performed on 'PROJECT' because it does not exist.
Error Code: 30000
Call: DROP TABLE PROJECT
Query: DataModifyQuery(sql="DROP TABLE PROJECT")
[EL Fine]: sql: Connection(2083819316)--CREATE TABLE TASK (TASK_ID INTEGER NOT NULL, COMPLETED SMALLINT DEFAULT 0, NAME VARCHAR(255), TARGET_NAME DATE, PROJECT_ID INTEGER, PRIMARY KEY (TASK_ID))
[EL Fine]: sql: Connection(1856779883)--CREATE TABLE PROJECT (PROJECT_ID INTEGER NOT NULL, DESCRIPTION VARCHAR(255), HEADLINE VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (PROJECT_ID))
[EL Fine]: sql: Connection(1201700471)--ALTER TABLE TASK ADD CONSTRAINT FK_TASK_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
[EL Fine]: sql: Connection(483173395)--SELECT SEQ_NAME FROM SEQUENCE WHERE SEQ_NAME <> SEQ_NAME
[EL Fine]: sql: Connection(378235680)--DELETE FROM SEQUENCE WHERE SEQ_NAME = SEQ_GEN
[EL Fine]: sql: Connection(1053449704)--SELECT * FROM SEQUENCE WHERE SEQ_NAME = SEQ_GEN
[EL Fine]: sql: Connection(731984020)--INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values (SEQ_GEN, 0)
[EL Fine]: sql: Connection(2054574154)--SELECT SEQ_NAME FROM SEQUENCE WHERE SEQ_NAME <> SEQ_NAME
DemoDataConfigurator.initialise() projectTaskService=je7hb.intro.xentracker.boundary.ProjectTaskService@5fd9a782
DemoDataConfigurator.createInitialProjectData() projectTaskService=je7hb.intro.xentracker.boundary.ProjectTaskService@5fd9a782
[EL Fine]: sql: Connection(1044124131)--UPDATE SEQUENCE SET SEQ_COUNT = SEQ_COUNT + ? WHERE SEQ_NAME = ?
	bind => [50, SEQ_GEN]
[EL Fine]: sql: Connection(1044124131)--SELECT SEQ_COUNT FROM SEQUENCE WHERE SEQ_NAME = ?
	bind => [SEQ_GEN]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO PROJECT (PROJECT_ID, DESCRIPTION, HEADLINE, NAME) VALUES (?, ?, ?, ?)
	bind => [6, important anniversary so tell immediate relatives not to miss it!, Grandparent Birthday, Family Birthday]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO PROJECT (PROJECT_ID, DESCRIPTION, HEADLINE, NAME) VALUES (?, ?, ?, ?)
	bind => [11, Renegotiate the principal account with the enrolled customer., Important phase in our sales strategy, Business Report]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO PROJECT (PROJECT_ID, DESCRIPTION, HEADLINE, NAME) VALUES (?, ?, ?, ?)
	bind => [1, Show off the project to the key stakeholders and decision makers, Demonstration of the Milestone 1, Technology Presentation]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [2, true, Design concept, 2014-04-25, 1]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [13, false, Hold the meeting, 2014-05-09, 11]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [9, true, Buy birthday card, 2014-04-26, 6]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [15, false, Furnish report to the boss, 2014-05-16, 11]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [4, false, Talk to the organizer, 2014-05-03, 1]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [14, false, Write the report, 2014-05-10, 11]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [10, false, Organize the party, 2014-05-04, 6]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [12, true, Set up a meeting, 2014-05-02, 11]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [5, false, Prepare demos, 2014-05-05, 1]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [8, false, Buy gifts, 2014-05-05, 6]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [7, true, Secretly find out gifts, 2014-05-07, 6]
[EL Fine]: sql: Connection(1044124131)--INSERT INTO TASK (TASK_ID, COMPLETED, NAME, TARGET_NAME, PROJECT_ID) VALUES (?, ?, ?, ?, ?)
	bind => [3, false, Write slides, 2014-05-01, 1]
=================================================
=================================================
=================================================

HIT THE RETURN KEY >
Stopping service ...
[EL Config]: connection: Connection(438548346)--disconnect
[EL Info]: connection: file:/C:/Users/Gareth/AppData/Local/Temp/gfembed1863456500632231034tmp/applications/xentracker/WEB-INF/classes/_XenTracker logout successful
PlainTextActionReporterSUCCESSNo monitoring data to report.
JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]

BUILD SUCCESSFUL

Total time: 5 mins 44.288 secs

**************************************************
Command line runtime capture.  Using 'gradle run'.
**************************************************

INFO: Initializing Mojarra 2.2.0 ( 20130502-2118 https://svn.java.net/svn/mojarr
a~svn/tags/2.2.0@11930) for context '/xentracker'
Apr 23, 2014 12:29:54 PM org.glassfish.jersey.server.ApplicationHandler initiali
ze
INFO: Initiating Jersey application, version Jersey: 2.0 2013-05-14 20:07:34...
Apr 23, 2014 12:29:55 PM org.glassfish.jersey.gf.ejb.EjbComponentProvider regist
erEjbInterceptor
INFO: The Jersey EJB interceptor is bound. JAX-RS EJB integration support is ena
bled.
Apr 23, 2014 12:29:55 PM com.sun.enterprise.web.WebApplication start
INFO: Loading application [xentracker] at [/xentracker]
Apr 23, 2014 12:30:02 PM com.sun.faces.application.resource.ResourceHandlerImpl
logMissingResource
WARNING: JSF1064: Unable to find or serve resource, /views/index.xhtml.
Apr 23, 2014 12:30:02 PM com.sun.faces.context.ExceptionHandlerImpl log
FATAL: JSF1073: javax.faces.FacesException caught during processing of RESTORE_V
IEW 1 : UIComponent-ClientId=, Message=com.sun.faces.context.FacesFileNotFoundEx
ception: /views/index.xhtml Not Found in ExternalContext as a Resource
Apr 23, 2014 12:30:02 PM com.sun.faces.context.ExceptionHandlerImpl log
FATAL: com.sun.faces.context.FacesFileNotFoundException: /views/index.xhtml Not
Found in ExternalContext as a Resource
javax.faces.FacesException: com.sun.faces.context.FacesFileNotFoundException: /v
iews/index.xhtml Not Found in ExternalContext as a Resource
        at com.sun.faces.application.view.ViewMetadataImpl.createMetadataView(Vi
ewMetadataImpl.java:117)
        at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.jav
a:241)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.jav
a:121)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)

        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java
:1682)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:344)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:214)
        at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletF
ilter.java:253)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:256)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:316)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.j
ava:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.jav
a:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.j
ava:359)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:260)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallab
le.call(ContainerMapper.java:496)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(Container
Mapper.java:175)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.
java:191)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.ja
va:168)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpSer
verFilter.java:187)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(Executor
Resolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(De
faultFilterChain.java:288)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart
(DefaultFilterChain.java:206)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultF
ilterChain.java:136)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultF
ilterChain.java:114)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.jav
a:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNI
OTransport.java:837)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(Abstr
actIOStrategy.java:113)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerTh
readIOStrategy.java:115)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(Wo
rkerThreadIOStrategy.java:55)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadR
unnable.run(WorkerThreadIOStrategy.java:135)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(Abs
tractThreadPool.java:565)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(Abstra
ctThreadPool.java:545)
        at java.lang.Thread.run(Thread.java:744)
Caused by: com.sun.faces.context.FacesFileNotFoundException: /views/index.xhtml
Not Found in ExternalContext as a Resource
        at com.sun.faces.facelets.impl.DefaultFaceletFactory.resolveURL(DefaultF
aceletFactory.java:274)
        at com.sun.faces.facelets.impl.DefaultFaceletFactory.resolveURL(DefaultF
aceletFactory.java:357)
        at com.sun.faces.facelets.impl.DefaultFaceletFactory.getMetadataFacelet(
DefaultFaceletFactory.java:250)
        at com.sun.faces.application.view.ViewMetadataImpl.createMetadataView(Vi
ewMetadataImpl.java:113)
        ... 38 more

Apr 23, 2014 12:35:16 PM org.glassfish.admin.mbeanserver.JMXStartupService shutd
own
INFO: JMXStartupService and JMXConnectors have been shut down.
Apr 23, 2014 12:35:16 PM com.sun.enterprise.connectors.service.ResourceAdapterAd
minServiceImpl sendStopToResourceAdapter
INFO: RAR7094: __ds_jdbc_ra shutdown successful.
Apr 23, 2014 12:35:16 PM com.sun.enterprise.v3.server.AppServerStartup stop
INFO: Shutdown procedure finished

I thought it should work without deploying the war file because of the embedded Glassfish server?

Kind regards,

Gareth

**Comment by peterpilgrim** [comment]
*DONE*
